version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: KeycloakSimpleFlashSale
    ports:
      - "7080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-config.json
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_IMPORT: /opt/keycloak/data/import/realm-config.json
    command: ["start-dev", "--import-realm"]
